function settings = getScreenSettings(window)
%GETSCREENSETTINGS Returns a structure with screen settings and some keys

[screenXpixels, screenYpixels] = Screen('WindowSize', window);

settings = struct('titleSize', 90, 'mainTextSize', 35, 'lowerTextSize', 25, 'trialTextSize', 100, ...
    'lowerTextPosition', screenYpixels * 0.85, 'titlePosition', screenYpixels * 0.2, ...
    'lowerRightPosition', screenXpixels * 0.8, 'lowerLeftPosition', screenXpixels * 0.05, ...
    'titleLines', repmat('_', 1, 50), 'upperLinePosition', screenYpixels * 0.1, ...
    'lowerLinePosition', screenYpixels * 0.23, ...
    'backwardKey', KbName('q'), 'forwardKey', KbName('space'), 'responseKey', KbName('space'), ...
    'backwardKeyText', 'Press "q" for previous page', 'forwardKeyText', 'Press Space to continue');

end